version: '3'

services:
  sidecar:
    image: tarfeef101/s3_sidecar:latest
    build: .
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "1"
    environment:
      - AWS_ACCESS_KEY_ID=
      - AWS_SECRET_ACCESS_KEY=
      - AWS_SESSION_TOKEN=
      - FILES=
      - BUCKET=
      - BASENAME=
    volumes:
      - ./mount:/opt
